<?php

namespace frontend\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\AccessControl;
use common\controllers\MasterController as MasterCommonController;

/**
 * Site controller
 */
class MasterController extends MasterCommonController
{

    public $layout = '/content';
    public $title = 'Title';
    public $subTitle = 'Sub Title';
    public $subSubTitle = 'Sub Sub Title';

    public function getTitle()
    {
        return $this->title;
    }

    public function getSubTitle()
    {
        return $this->subTitle;
    }

    public function getSubSubTitle()
    {
        return $this->subSubTitle;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->view->params['cart'] = [
            'total' => 123456,
            'qty' => 4,
            'items' => [
                [
                    'title' => 'Product 1',
                    'qty' => 3,
                    'price' => 1234,
                ],
                [
                    'title' => 'Product 2',
                    'qty' => 6,
                    'price' => 11234,
                ],
                [
                    'title' => 'Product 3',
                    'qty' => 4,
                    'price' => 12234,
                ],
                [
                    'title' => 'Product 4',
                    'qty' => 2,
                    'price' => 51234,
                ],
            ]
        ];
    }

}
