<?php

namespace frontend\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\AccessControl;
use common\controllers\MasterController as MasterCommonController;

/**
 * Site controller
 */
class MasterController extends MasterCommonController
{

    public $layout = '/content';
    public $title = 'Title';
    public $subTitle = 'Sub Title';
    public $subSubTitle = 'Sub Sub Title';

    public function getTitle()
    {
        return $this->title;
    }

    public function getSubTitle()
    {
        return $this->subTitle;
    }

    public function getSubSubTitle()
    {
        return $this->subSubTitle;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $session = Yii::$app->session;
        if (!isset($session['orderToken'])) {
            $session['orderToken'] = Yii::$app->security->generateRandomString();
        }
        $this->view->params['cart'] = \common\models\costfit\Order::findCartArray();
    }

}
