<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace common\helpers;

use Yii;
use yii\base\Model;
use yii\db\ActiveRecord;
use yii\data\ActiveDataProvider;

/**
 * Description of CozxyCalculatesCart
 * Create Date 21/09/2017
 * @author it
 * ฟังก์ชั่นของ PHP ที่ใช้สำหรับปัดเศษนั้น มีอยู่ทั้งหมด 3 ฟังก์ชั่น คือ floor() , ceil() และฟังก์ชั่น round() ที่ผมจะกล่าวในวันนี้
  ฟังก์ชั่น round() นั้นเราสา่มารถกำหนดได้ว่าจะเอาผลลัพธ์เป็นทศนิยมกี่ตำแหน่ง และการทำงานของฟังก์ชั่นนี้ ถ้าถึง 5 จะปัดขึ้น ถ้าน้อยกว่า 5 จะปัดลง
 * mode จะประกอบไปด้วย
  PHP_ROUND_HALF_UP : ถึง 5 ปัดขึ้น
  PHP_ROUND_HALF_DOWN : ต่อให้ถึง 5 ก็ปัดลง
  PHP_ROUND_HALF_EVEN : จำนวนเต็มเป็นเลขคี่และถึง 5 ปัดขึ้น
  PHP_ROUND_HALF_ODD : จำนวนเต็มเป็นเลขคู่และถึง 5 ปัดขึ้น

 * *
 * #############################################

 *  echo round( 1.54 );
  //2
  echo round( 1.216 ,2 );
  //1.22
  echo round( -1.555 ,2 );
  //-1.56
  echo round( -1.213,2 );
  //-1.21

 */
class CozxyCalculatesCart {

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        $Order = \common\models\costfit\Order::find()->where('userId=' . Yii::$app->user->id)->orderBy('orderId desc')->one();
        if (isset($Order->orderId)) {
            $OrderItemSumTotal = \common\models\costfit\OrderItem::find()->where('orderId=' . $Order->orderId)->sum('total');
        } else {
            $OrderItemSumTotal = 0;
        }
        if (isset($Order->couponId)) {
            $coupon = \common\models\costfit\Coupon::find()->where('couponId=' . $Order->couponId)->one();
            $couponValue = $coupon->discountValue;
        } else {
            $couponValue = 0;
        }
    }

    public static function UserOrder() {

        $Order = \common\models\costfit\Order::find()->where('userId=' . Yii::$app->user->id)->orderBy('orderId desc')->one();
        if (isset($Order->orderId)) {
            $OrderItemSumTotal = \common\models\costfit\OrderItem::find()->where('orderId=' . $Order->orderId)->sum('total');
        } else {
            $OrderItemSumTotal = 0;
        }
        if (isset($Order->couponId)) {
            $coupon = \common\models\costfit\Coupon::find()->where('couponId=' . $Order->couponId)->one();
            $couponValue = $coupon->discountValue;
        } else {
            $couponValue = 0;
        }
        $OrderTotle = $OrderItemSumTotal - $couponValue;
        return round($OrderTotle, 0, PHP_ROUND_HALF_UP);
    }

    /*
      $total = CozxyCalculatesCart::FormulaTotal($OrderItemSumTotal, $couponValue);
      $TotalExVat = CozxyCalculatesCart::FormulaTotalExVat($total);
      $vat = CozxyCalculatesCart::FormulaVAT($TotalExVat);
      $SubTotal = CozxyCalculatesCart::FormulaSubTotal($TotalExVat, $vat);
     */

    public static function FormulaTotal() {
        $result = \common\helpers\CozxyCalculatesCart::UserOrder();
        return round($result, 0, PHP_ROUND_HALF_UP);
    }

    /*
     * ราคาสินค้าไม่รวมภาษี
     */

    public static function FormulaTotalExVat() {
        $total = \common\helpers\CozxyCalculatesCart::UserOrder();
        $result = $total / 1.07;
        return round($result, 0, PHP_ROUND_HALF_UP);
    }

    /*
     * ภาษีมูลค่าเพิ่ม VAT 7%
     */

    public static function FormulaVAT() {
        $TotalExVat = \common\helpers\CozxyCalculatesCart::FormulaTotalExVat();
        $result = $TotalExVat * 0.07;
        return round($result, 0, PHP_ROUND_HALF_UP);
    }

    /*
     * สวนลดพิเศษ : Coupon
     */

    public static function FormulaExtraSaving() {

    }

    /*
     * ราคาสินค้ารวมภาษีมูลค่าเพิ่ม
     */

    public static function FormulaSubTotal() {
        $TotalExVat = \common\helpers\CozxyCalculatesCart::FormulaTotalExVat();
        $vat = \common\helpers\CozxyCalculatesCart::FormulaVAT();
        $result = ( $TotalExVat + $vat);
        return $result;
    }

    public static function TestCart() {
        echo $this->content;
    }

}
